//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineGame.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LineGame.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linegame.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        public static string BackgroundTitle {
            get {
                return ResourceManager.GetString("BackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ball.
        /// </summary>
        public static string BallTitle {
            get {
                return ResourceManager.GetString("BallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string btnPauseTitle {
            get {
                return ResourceManager.GetString("btnPauseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string btnResumeTitle {
            get {
                return ResourceManager.GetString("btnResumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string btnStartTitle {
            get {
                return ResourceManager.GetString("btnStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        public static string btnStopTitle {
            get {
                return ResourceManager.GetString("btnStopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davang Solutions.
        /// </summary>
        public static string CopyrightMessage {
            get {
                return ResourceManager.GetString("CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please start new game....
        /// </summary>
        public static string GameInitializedMessage {
            get {
                return ResourceManager.GetString("GameInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game is lost! please start new game....
        /// </summary>
        public static string GameLostMessage {
            get {
                return ResourceManager.GetString("GameLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game is paused! please resume game....
        /// </summary>
        public static string GamePausedMessage {
            get {
                return ResourceManager.GetString("GamePausedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game saved....
        /// </summary>
        public static string GameSavedMessage {
            get {
                return ResourceManager.GetString("GameSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game is stopped! please start new game....
        /// </summary>
        public static string GameStoppedMessage {
            get {
                return ResourceManager.GetString("GameStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high scores.
        /// </summary>
        public static string HistoryAppBarButtonText {
            get {
                return ResourceManager.GetString("HistoryAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balls.
        /// </summary>
        public static string HistoryBallTitle {
            get {
                return ResourceManager.GetString("HistoryBallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string HistoryDurationTitle {
            get {
                return ResourceManager.GetString("HistoryDurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lost on.
        /// </summary>
        public static string HistoryEntryDateLostTitle {
            get {
                return ResourceManager.GetString("HistoryEntryDateLostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped on.
        /// </summary>
        public static string HistoryEntryDateTitle {
            get {
                return ResourceManager.GetString("HistoryEntryDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves.
        /// </summary>
        public static string HistoryMoveTitle {
            get {
                return ResourceManager.GetString("HistoryMoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gameline - high scores.
        /// </summary>
        public static string HistoryPageTitle {
            get {
                return ResourceManager.GetString("HistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        public static string HistoryScoreTitle {
            get {
                return ResourceManager.GetString("HistoryScoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use number.
        /// </summary>
        public static string HistoryUseNumberTitle {
            get {
                return ResourceManager.GetString("HistoryUseNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string LoadGameMessage {
            get {
                return ResourceManager.GetString("LoadGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game over! your score is {0}.
        /// </summary>
        public static string LoseMessage {
            get {
                return ResourceManager.GetString("LoseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linegame - lost.
        /// </summary>
        public static string LostTitle {
            get {
                return ResourceManager.GetString("LostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string MoveCountTitle {
            get {
                return ResourceManager.GetString("MoveCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next balls:.
        /// </summary>
        public static string NextColorsTitle {
            get {
                return ResourceManager.GetString("NextColorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linegame - paused.
        /// </summary>
        public static string PausedTitle {
            get {
                return ResourceManager.GetString("PausedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pausing....
        /// </summary>
        public static string PauseGameMessage {
            get {
                return ResourceManager.GetString("PauseGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick background.
        /// </summary>
        public static string PickBackgroundTitle {
            get {
                return ResourceManager.GetString("PickBackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linegame - playing.
        /// </summary>
        public static string PlayingTitle {
            get {
                return ResourceManager.GetString("PlayingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string RatingMessage {
            get {
                return ResourceManager.GetString("RatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove ads.
        /// </summary>
        public static string RemoveAdsMessage {
            get {
                return ResourceManager.GetString("RemoveAdsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get more scores with balls in order.
        /// </summary>
        public static string ScoreExplanation {
            get {
                return ResourceManager.GetString("ScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        public static string ScoreTitle {
            get {
                return ResourceManager.GetString("ScoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gameline - settings.
        /// </summary>
        public static string SettingPageTitle {
            get {
                return ResourceManager.GetString("SettingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound enabled.
        /// </summary>
        public static string SoundEnabledMessage {
            get {
                return ResourceManager.GetString("SoundEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting....
        /// </summary>
        public static string StartGameMessage {
            get {
                return ResourceManager.GetString("StartGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linegame - stopped.
        /// </summary>
        public static string StoppedTitle {
            get {
                return ResourceManager.GetString("StoppedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated on 10/28/2014.
        /// </summary>
        public static string UpdateDateMessage {
            get {
                return ResourceManager.GetString("UpdateDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play with number.
        /// </summary>
        public static string UseNumberTitle {
            get {
                return ResourceManager.GetString("UseNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0}.
        /// </summary>
        public static string VersionMessage {
            get {
                return ResourceManager.GetString("VersionMessage", resourceCulture);
            }
        }
    }
}
